#         Makefile for GiST test program, Windows platform
#	  $Header: /usr/local/devel/GiST/libgist/src/examples/btree/Makefile.NT,v 1.1.1.1 1997/11/13 02:43:52 marcel Exp $

YACC = bison
YACCFLAGS = -d
LEX = flex

all: bt_gram_tab.cpp bt_scan.cpp

bt_gram_tab.cpp: bt_gram.y
	$(YACC) $(YACCFLAGS) $?
	rename bt_gram_tab.c $@

bt_scan.cpp: bt_scan.l
	$(LEX) $(LEXFLAGS) $?
	rename lexyy.c $@

clean:
	rm -f bt_gram_tab.* bt_scan.cpp
