#!/bin/csh

rm -rf btree.out bttemp btree
echo "running B-tree tests..."
ln -s ../src/examples/btree/btree .
./btree < bttest.script > btree.out
diff btree.out btree.std

rm -rf rtree.out rttemp rtree
echo "running R-tree tests..."
ln -s ../src/examples/rtree/rtree .
./rtree < rttest.script > rtree.out
diff rtree.out rtree.std
