#         Makefile for GiST test program, Windows platform
#	  $Header: /usr/local/devel/GiST/libgist/src/examples/rtree/Makefile.NT,v 1.1.1.1 1997/11/13 02:43:53 marcel Exp $

YACC = bison
YACCFLAGS = -d
LEX = flex

all: rt_gram_tab.cpp rt_scan.cpp

rt_gram_tab.cpp: rt_gram.y
	$(YACC) $(YACCFLAGS) $?
	rename rt_gram_tab.c $@

rt_scan.cpp: rt_scan.l
	$(LEX) $(LEXFLAGS) $?
	rename lexyy.c $@

clean:
	rm -f rt_gram_tab.* rt_scan.cpp
